[package]
name = "balloon"
version = "0.0.2"
description = "Balloon Hash with Blake2b"
authors = ["hello@organism.org"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/stichtingorganism/balloon"

[dependencies]
blake2b_simd = "0.5"
subtle = "2"
num-bigint = "0.2"
num-traits = "0.2"
elapsed = "0.1"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "balloon_benchmarks"
harness = false
